version: "3.9"
services:
    postgres:
        image: postgis/postgis:16-3.4-alpine
        restart: always
        environment:
            PGDATA: /data/
        env_file:
          - deployment/database.dev.env
        volumes:
          - ./api/database:/data
          - ./deployment/10_postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d planer_podrozy"]
            interval: 5s
            timeout: 5s
            retries: 15
    pgadmin:
        image: dpage/pgadmin4
        env_file:
          - deployment/database.pgadmin.dev.env
        ports:
          - "8081:8001"
        depends_on:
          - postgres
    api:
        build:
            context: ./
            dockerfile: ./deployment/Dockerfile.backend
        env_file:
          - deployment/database.dev.env
          - deployment/backend.dev.env
        ports:
          - "8000:8000"
        depends_on:
          postgres:
            condition: service_healthy
        restart: unless-stopped
        volumes:
          - ./api/src:/api/src
          - ./api/migrations:/api/migrations
          - ./api/alembic.ini:/api/alembic.ini

    ui:
        build:
            context: ./
            dockerfile: ./deployment/Dockerfile.frontend
        env_file:
          - deployment/frontend.dev.env
        ports:
          - "8080:8080"
        depends_on:
          - api
        restart: unless-stopped
        volumes:
          - ./ui/src:/ui/src
          - ./ui/index.html:/ui/index.html