version: "3.9"
services:
    postgres:
        image: postgres:15.1-alpine3.17
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: example
            POSTGRES_DB: planer_podrozy
            PGDATA: /data/
        volumes:
         - ./api/database:/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d planer_podrozy"]
            interval: 5s
            timeout: 5s
            retries: 10
    api:
        build:
            context: ./
            dockerfile: ./deployment/Dockerfile.backend
        ports:
          - "8000:8000"
        depends_on:
          postgres:
            condition: service_healthy
        restart: always
        volumes:
          - ./api/src:/api/