name: frontend-linters
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - frontend
    paths:
      - 'ui/**'
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: StyleLint
        run: npm run stylelint