name: Github-actions-backend

on:
  push:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: python-isort
  # You may pin to the exact commit or the version.
  # uses: isort/isort-action@f14e57e1d457956c45a19c05a89cccdf087846e5
        uses: isort/isort-action@v1
        with:
          # Version of isort to use
          isort-version: isort/isort-action@v5.1.0
          # files or directories to sort 
      - name: Black Check
        # uses: jpetrucciani/black-check@da5d255763b9112c07db0b6ee8be000edf3379a0
        uses: jpetrucciani/black-check@22.10.0
#       with:
#     # File or directory to run black on
#         path: # optional, default is .
