name: Github-actions-backend

on:
  push:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: python-isort
        uses: isort/isort-action@v1
        with:
          isort-version: isort/isort-action@v5.10.1 
      
      - name: Black Check
        uses: jpetrucciani/black-check@22.10.0
