name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./ui

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npx token-transformer tokens.json transformed-tokens.json
      - run: npx npx style-dictionary build --config style-dictionary-config.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update css tokens'